/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

import datos.SesionUsuario;
import entidades.Paciente;
import entidades.Rol;
import entidades.Usuario;
import logica.composite.CategoriaMenu;
import logica.composite.ItemMenu;
import logica.composite.MenuBuilder;

import javax.swing.*;
import java.util.ArrayList;

/**
 *
 * @author yordi
 */
public class FrmPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmPrincipal.class.getName());


    private Usuario usuarioActual;

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();

        usuarioActual = SesionUsuario.getInstance().getUsuario();

        lblUsuario.setText(usuarioActual.getUsername());
        lblRol.setText(usuarioActual.getRol().name());

        armarMenuDinamico();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        lblUsuario = new javax.swing.JLabel();
        lblRol = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        desktopPane.setBackground(new java.awt.Color(204, 204, 204));

        lblUsuario.setBackground(new java.awt.Color(255, 255, 255));
        lblUsuario.setFont(new java.awt.Font("Segoe UI Black", 1, 48)); // NOI18N
        lblUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsuario.setText("USUARIO");

        lblRol.setBackground(new java.awt.Color(255, 255, 255));
        lblRol.setFont(new java.awt.Font("Segoe UI Black", 1, 48)); // NOI18N
        lblRol.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRol.setText("ADMINISTRADOR");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("BIENVENIDO(A)");

        desktopPane.setLayer(lblUsuario, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(lblRol, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, desktopPaneLayout.createSequentialGroup()
                .addContainerGap(344, Short.MAX_VALUE)
                .addGroup(desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, desktopPaneLayout.createSequentialGroup()
                            .addComponent(lblRol, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(223, 223, 223))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, desktopPaneLayout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(583, 583, 583)))))
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(desktopPaneLayout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(jLabel1)
                .addGap(68, 68, 68)
                .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(lblRol, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(349, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        
        SesionUsuario.getInstance().cerrarSesion();
        
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmPrincipal().setVisible(true));
    }

    private void armarMenuDinamico(){
        JMenuBar barraPrincipal;

        barraPrincipal = MenuBuilder.crear()

                .agregarCategoria("Seguridad/Usuarios")
                    .agregarItem("Registrar Usuario", e -> { abrirInternalFrame(new IfrmRegistrarUsuario());},
                            Rol.ADMINISTRADOR)
                    .agregarItem("Buscar Usuario", e -> {abrirInternalFrame(new IfrmBuscarEditarEliminarUsuario());},
                            Rol.ADMINISTRADOR)
                    .agregarItem("Auditoria del Sistema ", e -> {abrirInternalFrame(new IfrmListarAuditorias());},
                            Rol.ADMINISTRADOR, Rol.DIRECTOR_MEDICO)
                    .agregarSeparador()
                    .agregarItem("Cerrar Sesion", e -> {
                        SesionUsuario.getInstance().cerrarSesion();
                        this.dispose();
                        FrmInicioSesion frmInicioSesion = new FrmInicioSesion();
                        frmInicioSesion.setVisible(true);
                        }, Rol.values())
                    .agregarItem("Salir", e -> {
                        SesionUsuario.getInstance().cerrarSesion();
                        this.dispose();
                    }, Rol.values())

                .agregarCategoria("Pacientes")
                    .agregarItem("Registrar Paciente", e -> {abrirInternalFrame(new IfrmRegistroPaciente());},
                            Rol.ADMINISTRADOR, Rol.RECEPCIONISTA)
                    .agregarItem("Buscar Paciente", e -> {abrirInternalFrame(new IfrmBuscarPaciente());},
                            Rol.ADMINISTRADOR, Rol.RECEPCIONISTA, Rol.MEDICO, Rol.ENFERMERA, Rol.CAJERO)

                .agregarCategoria("Medicos")
                    .agregarItem("Gestión de Medicos", e -> {abrirInternalFrame(new IfrmGestionMedicos());},
                            Rol.ADMINISTRADOR)
                    .agregarItem("Gestionar Horarios", e -> {abrirInternalFrame(new IfrmGestionHorarios());},
                            Rol.ADMINISTRADOR)
                    .agregarItem("Agenda Medica", e -> {abrirInternalFrame(new IfrmAgendaMedica());},
                            Rol.ADMINISTRADOR, Rol.RECEPCIONISTA, Rol.DIRECTOR_MEDICO)

                .agregarCategoria("Citas")
                    .agregarItem("Programar Cita", e -> {abrirInternalFrame(new IfrmAgendarCita());},
                            Rol.RECEPCIONISTA, Rol.ADMINISTRADOR)
                    .agregarItem("Reprogramar Cita", e -> {abrirInternalFrame(new IfrmReprogramarCita());},
                            Rol.RECEPCIONISTA, Rol.ADMINISTRADOR)

                .agregarCategoria("Atencion Medica")
                    .agregarItem("Formulario de Atencion Medica", e -> {abrirInternalFrame(new IfrmAtencionMedica());},
                            Rol.MEDICO)
                    .agregarItem("Solicitud de Examen de Laboratorio", e -> {abrirInternalFrame(new IfrmSolicitudLaboratorio());},
                            Rol.MEDICO)

                .agregarCategoria("Laboratorio")
                    .agregarItem("Solicitudes Pendientes", e -> {abrirInternalFrame(new IfrmLaboratorioAtencion());},
                            Rol.LABORATORISTA, Rol.ADMINISTRADOR)

                .agregarCategoria("Farmacia")
                    .agregarItem("Despacho y entrega de Medicamentos", e -> {abrirInternalFrame(new IfrmDespachoFarmacia());},
                            Rol.FARMACEUTICO)
                    .agregarItem("Inventario de Medicamentos", e -> {abrirInternalFrame(new IfrmInventarioMedicamentos());},
                            Rol.FARMACEUTICO, Rol.ADMINISTRADOR)

                .agregarCategoria("Caja")
                    .agregarItem("Registrar Pago", e -> {},
                            Rol.CAJERO)
                    .agregarItem("Emitir Comprobante", e -> {},
                            Rol.CAJERO)

                .agregarCategoria("Reportes")
                    .agregarItem("Pacientes Por Especialidad", e -> {},
                            Rol.DIRECTOR_MEDICO, Rol.ADMINISTRADOR)
                    .agregarItem("Ingresos Diarios", e -> {},
                            Rol.CAJERO, Rol.DIRECTOR_MEDICO, Rol.ADMINISTRADOR)
                    .agregarItem("Exportar Reportes", e -> {},
                            Rol.DIRECTOR_MEDICO, Rol.ADMINISTRADOR)

                .build(usuarioActual.getRol());


        this.setJMenuBar(barraPrincipal);
    }

    public void abrirInternalFrame(JInternalFrame frame) {
        if (frame == null) return;

        if (frame.getParent() == null) {
            desktopPane.add(frame);
        }

        int x = (desktopPane.getWidth() - frame.getWidth()) / 2;
        int y = (desktopPane.getHeight() - frame.getHeight()) / 2;

        x = Math.max(0, x);
        y = Math.max(0, y);

        frame.setLocation(x, y);
        frame.setVisible(true);

        try {
            frame.setSelected(true);
            frame.toFront();
        } catch (java.beans.PropertyVetoException e) {
            e.printStackTrace();
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblRol;
    private javax.swing.JLabel lblUsuario;
    // End of variables declaration//GEN-END:variables
}
