/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package presentacion;

import datos.ComprobanteDAO;
import entidades.Comprobante;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Cristopher
 */

public class IfrmComprobante extends javax.swing.JInternalFrame {

    /**
     * Creates new form IfrmComprobante
     */
    public IfrmComprobante() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPricipal = new javax.swing.JPanel();
        pnlBusqueda = new javax.swing.JPanel();
        IblTitulo3 = new javax.swing.JLabel();
        IblBuscarPor = new javax.swing.JLabel();
        cmbBuscarPor = new javax.swing.JComboBox<>();
        IblBusqueda = new javax.swing.JLabel();
        txtBusqueda = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        IblTitulo = new javax.swing.JLabel();
        spComprobantes = new javax.swing.JScrollPane();
        tblComprobantes = new javax.swing.JTable();
        pnlDetalle = new javax.swing.JPanel();
        IblTitulo4 = new javax.swing.JLabel();
        IblNumero = new javax.swing.JLabel();
        IblTipo = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        txtTipo = new javax.swing.JTextField();
        IblFecha = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        txtIdPago = new javax.swing.JTextField();
        IblIdPago = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        IblTotal = new javax.swing.JLabel();
        btnVerDetalle = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        btnImprimir = new javax.swing.JButton();

        pnlPricipal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        pnlBusqueda.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        IblTitulo3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        IblTitulo3.setText("Buscar Comprobante");

        IblBuscarPor.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        IblBuscarPor.setText("Busca por");

        cmbBuscarPor.setEditable(true);
        cmbBuscarPor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Número", "Paciente", "Fecha" }));

        IblBusqueda.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        IblBusqueda.setText("Valor");

        btnBuscar.setText("Buscar");
        btnBuscar.setToolTipText("");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBusquedaLayout = new javax.swing.GroupLayout(pnlBusqueda);
        pnlBusqueda.setLayout(pnlBusquedaLayout);
        pnlBusquedaLayout.setHorizontalGroup(
            pnlBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBusquedaLayout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(IblBuscarPor)
                .addGap(45, 45, 45)
                .addComponent(cmbBuscarPor, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(IblBusqueda)
                .addGap(33, 33, 33)
                .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(149, 149, 149)
                .addComponent(btnBuscar)
                .addGap(103, 103, 103))
            .addGroup(pnlBusquedaLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(IblTitulo3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlBusquedaLayout.setVerticalGroup(
            pnlBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBusquedaLayout.createSequentialGroup()
                .addComponent(IblTitulo3)
                .addGap(24, 24, 24)
                .addGroup(pnlBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IblBuscarPor)
                    .addComponent(cmbBuscarPor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IblBusqueda)
                    .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        IblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        IblTitulo.setText("GESTION DE COMPROBANTES");

        tblComprobantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblComprobantes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblComprobantesMouseClicked(evt);
            }
        });
        spComprobantes.setViewportView(tblComprobantes);

        pnlDetalle.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        IblTitulo4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        IblTitulo4.setText("Detalle del comprobante");

        IblNumero.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        IblNumero.setText("Numero");

        IblTipo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        IblTipo.setText("Tipo");

        txtNumero.setEditable(false);

        txtTipo.setEditable(false);

        IblFecha.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        IblFecha.setText("Fecha");

        txtFecha.setEditable(false);

        txtIdPago.setEditable(false);

        IblIdPago.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        IblIdPago.setText("ID Pago");

        txtTotal.setEditable(false);

        IblTotal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        IblTotal.setText("Total");

        javax.swing.GroupLayout pnlDetalleLayout = new javax.swing.GroupLayout(pnlDetalle);
        pnlDetalle.setLayout(pnlDetalleLayout);
        pnlDetalleLayout.setHorizontalGroup(
            pnlDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDetalleLayout.createSequentialGroup()
                .addGroup(pnlDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDetalleLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(IblTitulo4))
                    .addGroup(pnlDetalleLayout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addGroup(pnlDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(pnlDetalleLayout.createSequentialGroup()
                                .addComponent(IblNumero)
                                .addGap(34, 34, 34)
                                .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(89, 89, 89))
                            .addGroup(pnlDetalleLayout.createSequentialGroup()
                                .addComponent(IblIdPago)
                                .addGap(34, 34, 34)
                                .addComponent(txtIdPago, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlDetalleLayout.createSequentialGroup()
                                .addComponent(IblFecha)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(87, 87, 87)))
                        .addGap(18, 18, 18)
                        .addGroup(pnlDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(IblTipo)
                            .addComponent(IblTotal))
                        .addGap(41, 41, 41)
                        .addGroup(pnlDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTipo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlDetalleLayout.setVerticalGroup(
            pnlDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDetalleLayout.createSequentialGroup()
                .addComponent(IblTitulo4)
                .addGroup(pnlDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDetalleLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(pnlDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IblNumero))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtIdPago, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IblIdPago))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                        .addGroup(pnlDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(IblFecha)
                            .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(pnlDetalleLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IblTipo))
                        .addGap(18, 18, 18)
                        .addGroup(pnlDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IblTotal))
                        .addGap(18, 18, 18))))
        );

        btnVerDetalle.setText("Ver Detalle");
        btnVerDetalle.setToolTipText("");
        btnVerDetalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerDetalleActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.setToolTipText("");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnCerrar.setText("Cerrar");
        btnCerrar.setToolTipText("");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        btnImprimir.setText("Imprimir");
        btnImprimir.setToolTipText("");
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlPricipalLayout = new javax.swing.GroupLayout(pnlPricipal);
        pnlPricipal.setLayout(pnlPricipalLayout);
        pnlPricipalLayout.setHorizontalGroup(
            pnlPricipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPricipalLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(IblTitulo)
                .addGap(347, 347, 347))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPricipalLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(pnlPricipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPricipalLayout.createSequentialGroup()
                        .addGroup(pnlPricipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(pnlDetalle, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlPricipalLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(pnlPricipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pnlBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 830, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(spComprobantes, javax.swing.GroupLayout.PREFERRED_SIZE, 809, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(17, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPricipalLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnVerDetalle)
                        .addGap(94, 94, 94)
                        .addComponent(btnImprimir)
                        .addGap(113, 113, 113)
                        .addComponent(btnLimpiar)
                        .addGap(127, 127, 127)
                        .addComponent(btnCerrar)
                        .addGap(151, 151, 151))))
        );
        pnlPricipalLayout.setVerticalGroup(
            pnlPricipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPricipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(IblTitulo)
                .addGap(18, 18, 18)
                .addComponent(pnlBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(spComprobantes, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlDetalle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(pnlPricipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnImprimir)
                    .addComponent(btnVerDetalle)
                    .addComponent(btnLimpiar)
                    .addComponent(btnCerrar))
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlPricipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(pnlPricipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String criterio = cmbBuscarPor.getSelectedItem().toString();
        String valor = txtBusqueda.getText().trim();

        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tblComprobantes.getModel();
        modelo.setRowCount(0);

        try {
            if (valor.isEmpty()) {

                ArrayList<Comprobante> lista = ComprobanteDAO.listarComprobantes();

                if (lista.isEmpty()) {
                    JOptionPane.showMessageDialog(this, "No hay comprobantes registrados en el sistema.", "Sin registros", JOptionPane.INFORMATION_MESSAGE);
                    return;
                }

                for (Comprobante c : lista) {

                    modelo.addRow(new Object[]{
                        c.getNumeroComprobante(),
                        c.getFechaEmision(),
                        c.getTipoComprobante(),
                        String.format("%.2f", c.getTotal()),
                        c.getIdPago()
                    });
                }
            } else {

                if (criterio.equalsIgnoreCase("Número")) {
                    Comprobante c = ComprobanteDAO.buscarComprobantePorNumero(valor);

                    if (c == null) {
                        JOptionPane.showMessageDialog(this, "No se encontró ningún comprobante con el número: " + valor, "Sin resultados", JOptionPane.INFORMATION_MESSAGE);
                        return;
                    }

                    modelo.addRow(new Object[]{
                        c.getNumeroComprobante(),
                        c.getFechaEmision(),
                        c.getTipoComprobante(),
                        String.format("%.2f", c.getTotal()),
                        c.getIdPago()
                    });
                } else {
                    
                    try {
                        int id = Integer.parseInt(valor);
                        Comprobante c = ComprobanteDAO.buscarComprobante(id);

                        if (c == null) {
                            JOptionPane.showMessageDialog(this, "No se encontró ningún comprobante con el ID: " + id, "Sin resultados", JOptionPane.INFORMATION_MESSAGE);
                            return;
                        }

                        modelo.addRow(new Object[]{
                            c.getNumeroComprobante(),
                            c.getFechaEmision(),
                            c.getTipoComprobante(),
                            String.format("%.2f", c.getTotal()),
                            c.getIdPago()
                        });
                    } catch (NumberFormatException e) {
                        JOptionPane.showMessageDialog(this, "Para buscar por ID, ingrese un valor numérico válido.", "Error de formato", JOptionPane.WARNING_MESSAGE);
                    }
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocurrió un error al consultar la base de datos: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void tblComprobantesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblComprobantesMouseClicked

    }//GEN-LAST:event_tblComprobantesMouseClicked

    private void btnVerDetalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerDetalleActionPerformed
        /// 1. Validar que el usuario haya seleccionado una fila de la tabla
    int filaSeleccionada = tblComprobantes.getSelectedRow();

    if (filaSeleccionada == -1) {
        JOptionPane.showMessageDialog(this, 
            "Por favor, seleccione un comprobante de la tabla para ver su detalle.", 
            "Selección requerida", 
            JOptionPane.WARNING_MESSAGE);
        return;
    }

    // 2. Extraer los datos de la fila seleccionada segun el orden cargado en el boton Buscar:
    // Columna 0: Numero | Columna 1: Fecha | Columna 2: Tipo | Columna 3: Total | Columna 4: ID Pago
    String numero = tblComprobantes.getValueAt(filaSeleccionada, 0).toString();
    String fecha = tblComprobantes.getValueAt(filaSeleccionada, 1).toString();
    String tipo = tblComprobantes.getValueAt(filaSeleccionada, 2).toString();
    String total = tblComprobantes.getValueAt(filaSeleccionada, 3).toString();
    String idPago = tblComprobantes.getValueAt(filaSeleccionada, 4).toString();

    // 3. Asignar los valores directamente a los campos de la interfaz
    txtNumero.setText(numero);
    txtFecha.setText(fecha);
    txtTipo.setText(tipo);
    txtTotal.setText(total);
    txtIdPago.setText(idPago);
    }//GEN-LAST:event_btnVerDetalleActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        txtBusqueda.setText("");
        txtNumero.setText("");
        txtIdPago.setText("");
        txtFecha.setText("");
        txtTipo.setText("");
        txtTotal.setText("");

        cmbBuscarPor.setSelectedIndex(0);

        tblComprobantes.clearSelection();

        txtBusqueda.requestFocus();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
        // 1. Validar que exista un comprobante seleccionado en el detalle
    String numero = txtNumero.getText().trim();

    if (numero.isEmpty()) {
        JOptionPane.showMessageDialog(this, 
            "Debe seleccionar un comprobante de la tabla y presionar 'Ver Detalle' antes de imprimir.", 
            "Atención", 
            JOptionPane.WARNING_MESSAGE);
        return;
    }

    // 2. Obtener los datos cargados en las cajas de texto
    String fecha = txtFecha.getText();
    String tipo = txtTipo.getText();
    String total = txtTotal.getText();
    String idPago = txtIdPago.getText(); 

    // 3. Diseñar la estructura del ticket
    StringBuilder ticket = new StringBuilder();
    ticket.append("=========================================\n");
    ticket.append("          COMPROBANTE DE PAGO            \n");
    ticket.append("=========================================\n");
    ticket.append(" Tipo Comprobante : ").append(tipo).append("\n");
    ticket.append(" Nro. Comprobante : ").append(numero).append("\n");
    ticket.append(" Fecha de Emision : ").append(fecha).append("\n");
    ticket.append(" ID Pago Ref.     : ").append(idPago).append("\n");
    ticket.append("-----------------------------------------\n");
    ticket.append(" TOTAL COMPROBANTE: S/ ").append(total).append("\n");
    ticket.append("=========================================\n");
    ticket.append("        ¡Gracias por su preferencia!     \n");

    
    javax.swing.JTextArea textArea = new javax.swing.JTextArea(ticket.toString());
    textArea.setFont(new java.awt.Font("Monospaced", java.awt.Font.PLAIN, 12));
    textArea.setEditable(false);
    textArea.setOpaque(false);

    
    JOptionPane.showMessageDialog(this, 
        textArea, 
        "Vista Previa de Impresión - " + numero, 
        JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnImprimirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IblBuscarPor;
    private javax.swing.JLabel IblBusqueda;
    private javax.swing.JLabel IblFecha;
    private javax.swing.JLabel IblIdPago;
    private javax.swing.JLabel IblNumero;
    private javax.swing.JLabel IblTipo;
    private javax.swing.JLabel IblTitulo;
    private javax.swing.JLabel IblTitulo3;
    private javax.swing.JLabel IblTitulo4;
    private javax.swing.JLabel IblTotal;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnVerDetalle;
    private javax.swing.JComboBox<String> cmbBuscarPor;
    private javax.swing.JPanel pnlBusqueda;
    private javax.swing.JPanel pnlDetalle;
    private javax.swing.JPanel pnlPricipal;
    private javax.swing.JScrollPane spComprobantes;
    private javax.swing.JTable tblComprobantes;
    private javax.swing.JTextField txtBusqueda;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtIdPago;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtTipo;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
