/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package presentacion;
import entidades.ExamenLaboratorio;
import entidades.Paciente;
import logica.LaboratorioLOG;
import logica.PacienteLOG;
import javax.swing.JOptionPane;
/**
 *
 * @author LENOVO
 */
public class IfrmSolicitudLaboratorio extends javax.swing.JInternalFrame {

    /**
     * Creates new form IfrmSolicitudLaboratorio
     */
    public IfrmSolicitudLaboratorio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblPaciente = new javax.swing.JLabel();
        txtNHistoriaPaciente = new javax.swing.JTextField();
        lblTipoExamen = new javax.swing.JLabel();
        cmbTipoExamen = new javax.swing.JComboBox<>();
        lblObservacion = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtObservacion = new javax.swing.JTextArea();
        btnRegistrar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Registrar Solicitud de Examen de Laboratorio");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setText("Nueva Solicitud de Examen");

        lblPaciente.setText("N Historia del Paciente");

        lblTipoExamen.setText("Tipo de Examen :");

        cmbTipoExamen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hemograma Completo", "Examen de Orina", "Perfil Lipidico", "Glucosa de Sangre", "Prueba Hepatica" }));

        lblObservacion.setText("Observaciones :");

        txtObservacion.setColumns(20);
        txtObservacion.setRows(5);
        jScrollPane1.setViewportView(txtObservacion);

        btnRegistrar.setText("Generar Orden");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(lblPaciente)
                                    .addGap(59, 59, 59))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(lblTipoExamen)
                                    .addGap(78, 78, 78)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblObservacion)
                                .addGap(85, 85, 85)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbTipoExamen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNHistoriaPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(159, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(btnRegistrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancelar)
                .addGap(94, 94, 94))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPaciente)
                    .addComponent(txtNHistoriaPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipoExamen, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbTipoExamen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblObservacion)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(btnRegistrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        String numHistoria = txtNHistoriaPaciente.getText().trim();
        String tipoExamen = cmbTipoExamen.getSelectedItem() != null ? cmbTipoExamen.getSelectedItem().toString() : "";

        // Validacion de campo
        if (numHistoria.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor ingrese el número de historia clínica del paciente.", "Campo Requerido", JOptionPane.WARNING_MESSAGE);
            txtNHistoriaPaciente.requestFocus();
            return;
        }

        // Validar que la historia clinica exista y pertenezca a un paciente registrado
        Paciente paciente = PacienteLOG.buscarPorHistoriaClinica(numHistoria);
        if (paciente == null) {
            JOptionPane.showMessageDialog(this, "No se encontró un paciente registrado con la historia clínica: " + numHistoria, "Paciente no encontrado", JOptionPane.WARNING_MESSAGE);
            txtNHistoriaPaciente.requestFocus();
            return;
        }

        // Creamos el objeto ExamenLaboratorio
        ExamenLaboratorio examen = new ExamenLaboratorio();
        examen.setIdPaciente(paciente.getIdPaciente());
        examen.setTipoExamen(tipoExamen);
        examen.setEstado("Pendiente");
        examen.setObservaciones(txtObservacion.getText().trim());

        LaboratorioLOG laboratorioLOG = new LaboratorioLOG();
        try {
            boolean exito = laboratorioLOG.registrarSolicitud(examen);

            if (exito) {
                JOptionPane.showMessageDialog(this, "Solicitud de laboratorio registrada con éxito.", "Orden Creada", JOptionPane.INFORMATION_MESSAGE);
                txtNHistoriaPaciente.setText("");
                cmbTipoExamen.setSelectedIndex(0);
                txtObservacion.setText("");
                txtNHistoriaPaciente.requestFocus();
            } else {
                JOptionPane.showMessageDialog(this, "No se pudo registrar la solicitud.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error al procesar la solicitud: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<String> cmbTipoExamen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblObservacion;
    private javax.swing.JLabel lblPaciente;
    private javax.swing.JLabel lblTipoExamen;
    private javax.swing.JTextField txtNHistoriaPaciente;
    private javax.swing.JTextArea txtObservacion;
    // End of variables declaration//GEN-END:variables
}
