/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package presentacion;

import datos.ComprobanteDAO;
import entidades.Comprobante;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Cristopher
 */
public class IfrmComprobante extends javax.swing.JInternalFrame {

    /**
     * Creates new form IfrmComprobante
     */
    public IfrmComprobante() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPricipal = new javax.swing.JPanel();
        pnlBusqueda = new javax.swing.JPanel();
        IblTitulo3 = new javax.swing.JLabel();
        IblBusqueda = new javax.swing.JLabel();
        txtBusqueda = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        IblTitulo = new javax.swing.JLabel();
        pnlDetalle = new javax.swing.JPanel();
        IblTitulo4 = new javax.swing.JLabel();
        IblNumero = new javax.swing.JLabel();
        IblTipo = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        txtTipo = new javax.swing.JTextField();
        IblFecha = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        txtIdPago = new javax.swing.JTextField();
        IblIdPago = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        IblTotal = new javax.swing.JLabel();
        btnVerDetalle = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        btnImprimir = new javax.swing.JButton();
        spComprobantes = new javax.swing.JScrollPane();
        tblComprobantes = new javax.swing.JTable();

        pnlPricipal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        pnlBusqueda.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        IblTitulo3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        IblTitulo3.setText("Buscar Comprobante");

        IblBusqueda.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        IblBusqueda.setText("Número de comprobante:");

        btnBuscar.setText("Buscar");
        btnBuscar.setToolTipText("");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBusquedaLayout = new javax.swing.GroupLayout(pnlBusqueda);
        pnlBusqueda.setLayout(pnlBusquedaLayout);
        pnlBusquedaLayout.setHorizontalGroup(
            pnlBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBusquedaLayout.createSequentialGroup()
                .addContainerGap(178, Short.MAX_VALUE)
                .addComponent(IblBusqueda)
                .addGap(49, 49, 49)
                .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(114, 114, 114)
                .addComponent(btnBuscar)
                .addGap(149, 149, 149))
            .addGroup(pnlBusquedaLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(IblTitulo3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlBusquedaLayout.setVerticalGroup(
            pnlBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBusquedaLayout.createSequentialGroup()
                .addComponent(IblTitulo3)
                .addGap(24, 24, 24)
                .addGroup(pnlBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IblBusqueda)
                    .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        IblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        IblTitulo.setText("GESTION DE COMPROBANTES");

        pnlDetalle.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        IblTitulo4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        IblTitulo4.setText("Detalle del comprobante");

        IblNumero.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        IblNumero.setText("Numero");

        IblTipo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        IblTipo.setText("Tipo");

        txtNumero.setEditable(false);

        txtTipo.setEditable(false);

        IblFecha.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        IblFecha.setText("Fecha");

        txtFecha.setEditable(false);

        txtIdPago.setEditable(false);

        IblIdPago.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        IblIdPago.setText("ID Pago");

        txtTotal.setEditable(false);

        IblTotal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        IblTotal.setText("Total");

        javax.swing.GroupLayout pnlDetalleLayout = new javax.swing.GroupLayout(pnlDetalle);
        pnlDetalle.setLayout(pnlDetalleLayout);
        pnlDetalleLayout.setHorizontalGroup(
            pnlDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDetalleLayout.createSequentialGroup()
                .addGroup(pnlDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDetalleLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(IblTitulo4))
                    .addGroup(pnlDetalleLayout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addGroup(pnlDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlDetalleLayout.createSequentialGroup()
                                .addComponent(IblFecha)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlDetalleLayout.createSequentialGroup()
                                .addComponent(IblNumero)
                                .addGap(34, 34, 34)
                                .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlDetalleLayout.createSequentialGroup()
                                .addComponent(IblIdPago)
                                .addGap(34, 34, 34)
                                .addComponent(txtIdPago, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(63, 63, 63)
                        .addGroup(pnlDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(IblTipo)
                            .addComponent(IblTotal))
                        .addGroup(pnlDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlDetalleLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                                .addComponent(txtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlDetalleLayout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(txtTotal)))))
                .addGap(165, 165, 165))
        );
        pnlDetalleLayout.setVerticalGroup(
            pnlDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDetalleLayout.createSequentialGroup()
                .addComponent(IblTitulo4)
                .addGroup(pnlDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDetalleLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(pnlDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IblNumero))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtIdPago, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IblIdPago))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                        .addGroup(pnlDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(IblFecha)
                            .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(pnlDetalleLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IblTipo))
                        .addGap(18, 18, 18)
                        .addGroup(pnlDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IblTotal))
                        .addGap(18, 18, 18))))
        );

        btnVerDetalle.setText("Ver Detalle");
        btnVerDetalle.setToolTipText("");
        btnVerDetalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerDetalleActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.setToolTipText("");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnCerrar.setText("Cerrar");
        btnCerrar.setToolTipText("");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        btnImprimir.setText("Imprimir");
        btnImprimir.setToolTipText("");
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });

        tblComprobantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "NUMERO", "ID PAGO", "FECHA", "TIPO", "TOTAL"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        spComprobantes.setViewportView(tblComprobantes);

        javax.swing.GroupLayout pnlPricipalLayout = new javax.swing.GroupLayout(pnlPricipal);
        pnlPricipal.setLayout(pnlPricipalLayout);
        pnlPricipalLayout.setHorizontalGroup(
            pnlPricipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPricipalLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(IblTitulo)
                .addGap(347, 347, 347))
            .addGroup(pnlPricipalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnVerDetalle)
                .addGap(94, 94, 94)
                .addComponent(btnImprimir)
                .addGap(113, 113, 113)
                .addComponent(btnLimpiar)
                .addGap(127, 127, 127)
                .addComponent(btnCerrar)
                .addGap(151, 151, 151))
            .addGroup(pnlPricipalLayout.createSequentialGroup()
                .addGroup(pnlPricipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlPricipalLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(pnlDetalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 29, Short.MAX_VALUE))
            .addGroup(pnlPricipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPricipalLayout.createSequentialGroup()
                    .addContainerGap(15, Short.MAX_VALUE)
                    .addComponent(spComprobantes, javax.swing.GroupLayout.PREFERRED_SIZE, 906, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(36, Short.MAX_VALUE)))
        );
        pnlPricipalLayout.setVerticalGroup(
            pnlPricipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPricipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(IblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlDetalle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(152, 152, 152)
                .addGroup(pnlPricipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnImprimir)
                    .addComponent(btnVerDetalle)
                    .addComponent(btnLimpiar)
                    .addComponent(btnCerrar))
                .addGap(15, 15, 15))
            .addGroup(pnlPricipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPricipalLayout.createSequentialGroup()
                    .addContainerGap(323, Short.MAX_VALUE)
                    .addComponent(spComprobantes, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(46, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlPricipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(pnlPricipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        try {
            String numero = txtBusqueda.getText().trim();
            if (numero.isEmpty()) {
                JOptionPane.showMessageDialog(this,
                        "Ingrese el número del comprobante.",
                        "Dato requerido",
                        JOptionPane.WARNING_MESSAGE);
                return;
            }
            Comprobante comprobante = ComprobanteDAO.buscarComprobantePorNumero(numero);

            if (comprobante == null) {
                JOptionPane.showMessageDialog(this,
                        "No se encontró el comprobante.",
                        "Búsqueda",
                        JOptionPane.INFORMATION_MESSAGE);
                return;
            }

            DefaultTableModel modelo = (DefaultTableModel) tblComprobantes.getModel();
            modelo.setRowCount(0);

            modelo.addRow(new Object[]{
                comprobante.getNumeroComprobante(),
                comprobante.getIdPago(),
                comprobante.getFechaEmision(),
                comprobante.getTipoComprobante(),
                comprobante.getTotal()
            });

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnVerDetalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerDetalleActionPerformed
        /// 1. Validar que el usuario haya seleccionado una fila de la tabla
    int filaSeleccionada = tblComprobantes.getSelectedRow();

        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(this,
                    "Por favor, seleccione un comprobante de la tabla para ver su detalle.",
                    "Selección requerida",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        // 2. Extraer los datos de la fila seleccionada segun el orden cargado en el boton Buscar:
        // Columna 0: Numero | Columna 1: Fecha | Columna 2: Tipo | Columna 3: Total | Columna 4: ID Pago
        String numero = tblComprobantes.getValueAt(filaSeleccionada, 0).toString();
        String fecha = tblComprobantes.getValueAt(filaSeleccionada, 1).toString();
        String tipo = tblComprobantes.getValueAt(filaSeleccionada, 2).toString();
        String total = tblComprobantes.getValueAt(filaSeleccionada, 3).toString();
        String idPago = tblComprobantes.getValueAt(filaSeleccionada, 4).toString();

        // 3. Asignar los valores directamente a los campos de la interfaz
        txtNumero.setText(numero);
        txtFecha.setText(fecha);
        txtTipo.setText(tipo);
        txtTotal.setText(total);
        txtIdPago.setText(idPago);
    }//GEN-LAST:event_btnVerDetalleActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        txtBusqueda.setText("");
        txtNumero.setText("");
        txtIdPago.setText("");
        txtFecha.setText("");
        txtTipo.setText("");
        txtTotal.setText("");

     
        tblComprobantes.clearSelection();

        txtBusqueda.requestFocus();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
        // 1. Validar que exista un comprobante seleccionado en el detalle
        String numero = txtNumero.getText().trim();

        if (numero.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Debe seleccionar un comprobante de la tabla y presionar 'Ver Detalle' antes de imprimir.",
                    "Atención",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        // 2. Obtener los datos cargados en las cajas de texto
        String fecha = txtFecha.getText();
        String tipo = txtTipo.getText();
        String total = txtTotal.getText();
        String idPago = txtIdPago.getText();

        // 3. Diseñar la estructura del ticket
        StringBuilder ticket = new StringBuilder();
        ticket.append("=========================================\n");
        ticket.append("          COMPROBANTE DE PAGO            \n");
        ticket.append("=========================================\n");
        ticket.append(" Tipo Comprobante : ").append(tipo).append("\n");
        ticket.append(" Nro. Comprobante : ").append(numero).append("\n");
        ticket.append(" Fecha de Emision : ").append(fecha).append("\n");
        ticket.append(" ID Pago Ref.     : ").append(idPago).append("\n");
        ticket.append("-----------------------------------------\n");
        ticket.append(" TOTAL COMPROBANTE: S/ ").append(total).append("\n");
        ticket.append("=========================================\n");
        ticket.append("        ¡Gracias por su preferencia!     \n");

        javax.swing.JTextArea textArea = new javax.swing.JTextArea(ticket.toString());
        textArea.setFont(new java.awt.Font("Monospaced", java.awt.Font.PLAIN, 12));
        textArea.setEditable(false);
        textArea.setOpaque(false);

        JOptionPane.showMessageDialog(this,
                textArea,
                "Vista Previa de Impresión - " + numero,
                JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnImprimirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IblBusqueda;
    private javax.swing.JLabel IblFecha;
    private javax.swing.JLabel IblIdPago;
    private javax.swing.JLabel IblNumero;
    private javax.swing.JLabel IblTipo;
    private javax.swing.JLabel IblTitulo;
    private javax.swing.JLabel IblTitulo3;
    private javax.swing.JLabel IblTitulo4;
    private javax.swing.JLabel IblTotal;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnVerDetalle;
    private javax.swing.JPanel pnlBusqueda;
    private javax.swing.JPanel pnlDetalle;
    private javax.swing.JPanel pnlPricipal;
    private javax.swing.JScrollPane spComprobantes;
    private javax.swing.JTable tblComprobantes;
    private javax.swing.JTextField txtBusqueda;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtIdPago;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtTipo;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
