/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package presentacion;

import datos.AtencionMedicaDAO;
import entidades.AtencionMedica;
import entidades.DetalleReceta;
import entidades.Medicamento;
import entidades.Pago;
import entidades.RecetaMedica;
import java.time.LocalDate;
import javax.swing.JOptionPane;
import logica.CajaLOG;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import javax.swing.table.DefaultTableModel;
import logica.AtencionMedicaLOG;
import logica.FarmaciaLOG;

/**
 *
 * @author Cristopher
 */
public class IfrmCobroCaja extends javax.swing.JInternalFrame {

    /**
     * Creates new form IfrmCobroCaja
     */
    public IfrmCobroCaja() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        IblTitulo = new javax.swing.JLabel();
        pnlDatos = new javax.swing.JPanel();
        IblAtencion = new javax.swing.JLabel();
        txtAtencion = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        pnlPago = new javax.swing.JPanel();
        IblTitulo2 = new javax.swing.JLabel();
        IblMetodo = new javax.swing.JLabel();
        cmbMetodoPago = new javax.swing.JComboBox<>();
        cmbTipoComprobante = new javax.swing.JComboBox<>();
        IblComprobante = new javax.swing.JLabel();
        btnCobrar = new javax.swing.JButton();
        btnComprobante = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        spMedicamentos = new javax.swing.JScrollPane();
        tblMedicamentos = new javax.swing.JTable();
        IblTotal1 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();

        pnlPrincipal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        IblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        IblTitulo.setText("COBRO EN CAJA");

        pnlDatos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        IblAtencion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        IblAtencion.setText("ID Atención");

        btnBuscar.setText("Buscar atención");
        btnBuscar.setToolTipText("");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlDatosLayout = new javax.swing.GroupLayout(pnlDatos);
        pnlDatos.setLayout(pnlDatosLayout);
        pnlDatosLayout.setHorizontalGroup(
            pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosLayout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(IblAtencion)
                .addGap(73, 73, 73)
                .addComponent(txtAtencion, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84)
                .addComponent(btnBuscar)
                .addContainerGap(162, Short.MAX_VALUE))
        );
        pnlDatosLayout.setVerticalGroup(
            pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAtencion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IblAtencion)
                    .addComponent(btnBuscar))
                .addGap(19, 19, 19))
        );

        pnlPago.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        IblTitulo2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        IblTitulo2.setText("Datos del Pago");

        IblMetodo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        IblMetodo.setText("Metodo de Pago");

        cmbMetodoPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Efectivo", "Tarjeta", "Transferencia", "Yape", "Plin" }));

        cmbTipoComprobante.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Boleta", "Factura" }));

        IblComprobante.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        IblComprobante.setText("Tipo de Comprobante");

        javax.swing.GroupLayout pnlPagoLayout = new javax.swing.GroupLayout(pnlPago);
        pnlPago.setLayout(pnlPagoLayout);
        pnlPagoLayout.setHorizontalGroup(
            pnlPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPagoLayout.createSequentialGroup()
                .addGroup(pnlPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPagoLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(IblMetodo)
                        .addGap(44, 44, 44)
                        .addComponent(cmbMetodoPago, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(92, 92, 92)
                        .addComponent(IblComprobante)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbTipoComprobante, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlPagoLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(IblTitulo2)))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        pnlPagoLayout.setVerticalGroup(
            pnlPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPagoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(IblTitulo2)
                .addGap(17, 17, 17)
                .addGroup(pnlPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IblMetodo)
                    .addComponent(cmbMetodoPago, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IblComprobante)
                    .addComponent(cmbTipoComprobante, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnCobrar.setText("Registrar Cobro");
        btnCobrar.setToolTipText("");
        btnCobrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCobrarActionPerformed(evt);
            }
        });

        btnComprobante.setText("Ver Comprobante");
        btnComprobante.setToolTipText("");
        btnComprobante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprobanteActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.setToolTipText("");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnCerrar.setText("Cerrar");
        btnCerrar.setToolTipText("");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        tblMedicamentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MEDICAMENTO", "CANTIDAD", "PRECIO", "SUBTOTAL"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblMedicamentos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMedicamentosMouseClicked(evt);
            }
        });
        spMedicamentos.setViewportView(tblMedicamentos);
        if (tblMedicamentos.getColumnModel().getColumnCount() > 0) {
            tblMedicamentos.getColumnModel().getColumn(1).setResizable(false);
            tblMedicamentos.getColumnModel().getColumn(2).setResizable(false);
            tblMedicamentos.getColumnModel().getColumn(3).setResizable(false);
        }

        IblTotal1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        IblTotal1.setText("TOTAL");

        lblTotal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTotal.setText("S/. 0.00");

        javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipalLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(btnCobrar)
                .addGap(87, 87, 87)
                .addComponent(btnComprobante)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLimpiar)
                .addGap(91, 91, 91)
                .addComponent(btnCerrar)
                .addGap(94, 94, 94))
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addGap(314, 314, 314)
                        .addComponent(IblTitulo))
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(pnlPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(spMedicamentos, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlPrincipalLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(pnlDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addGap(399, 399, 399)
                        .addComponent(IblTotal1)
                        .addGap(59, 59, 59)
                        .addComponent(lblTotal)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        pnlPrincipalLayout.setVerticalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(IblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(spMedicamentos, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IblTotal1)
                    .addComponent(lblTotal))
                .addGap(10, 10, 10)
                .addComponent(pnlPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnComprobante)
                    .addComponent(btnCobrar)
                    .addComponent(btnLimpiar)
                    .addComponent(btnCerrar))
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(pnlPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCobrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCobrarActionPerformed


    }//GEN-LAST:event_btnCobrarActionPerformed

    private void btnComprobanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprobanteActionPerformed
        IfrmComprobante frm = new IfrmComprobante();
        getDesktopPane().add(frm);
        frm.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnComprobanteActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        txtAtencion.setText("");

        cmbMetodoPago.setSelectedIndex(0);
        cmbTipoComprobante.setSelectedIndex(0);

        txtAtencion.requestFocus();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void tblMedicamentosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMedicamentosMouseClicked

    }//GEN-LAST:event_tblMedicamentosMouseClicked

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        try {

            if (txtAtencion.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this,
                        "Ingrese el ID de la atención.",
                        "Dato requerido",
                        JOptionPane.WARNING_MESSAGE);
                return;
            }

            int idAtencion = Integer.parseInt(txtAtencion.getText().trim());

            AtencionMedica atencion = AtencionMedicaDAO.buscarPorId(idAtencion);

            if (atencion == null) {
                JOptionPane.showMessageDialog(this,
                        "No existe la atención médica.",
                        "Búsqueda",
                        JOptionPane.INFORMATION_MESSAGE);
                return;
            }

            RecetaMedica receta = atencion.getReceta();

            if (receta == null || !receta.tieneDetalles()) {
                JOptionPane.showMessageDialog(this,
                        "La atención no tiene medicamentos registrados.",
                        "Información",
                        JOptionPane.INFORMATION_MESSAGE);
                return;
            }

            DefaultTableModel modelo = (DefaultTableModel) tblMedicamentos.getModel();
            modelo.setRowCount(0);

            FarmaciaLOG farmacia = new FarmaciaLOG();

            double total = 0;

            for (DetalleReceta detalle : receta.getDetalles()) {

                Medicamento medicamento = farmacia.obtenerMedicamento(detalle.getIdMedicamento());

                double precio = medicamento.getPrecioUnitario();
                double subtotal = precio * detalle.getCantidad();

                modelo.addRow(new Object[]{
                    medicamento.getNombre(),
                    detalle.getCantidad(),
                    precio,
                    subtotal
                });

                total += subtotal;
            }

            lblTotal.setText(String.format("S/. %.2f", total));

        } catch (NumberFormatException e) {

            JOptionPane.showMessageDialog(this,
                    "El ID de atención debe ser numérico.",
                    "Error",
                    JOptionPane.WARNING_MESSAGE);

        } catch (Exception e) {

            JOptionPane.showMessageDialog(this,
                    e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IblAtencion;
    private javax.swing.JLabel IblComprobante;
    private javax.swing.JLabel IblMetodo;
    private javax.swing.JLabel IblTitulo;
    private javax.swing.JLabel IblTitulo2;
    private javax.swing.JLabel IblTotal1;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnCobrar;
    private javax.swing.JButton btnComprobante;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JComboBox<String> cmbMetodoPago;
    private javax.swing.JComboBox<String> cmbTipoComprobante;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JPanel pnlDatos;
    private javax.swing.JPanel pnlPago;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JScrollPane spMedicamentos;
    private javax.swing.JTable tblMedicamentos;
    private javax.swing.JTextField txtAtencion;
    // End of variables declaration//GEN-END:variables
}
