/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package presentacion;
import logica.LaboratorioLOG;
import entidades.ExamenLaboratorio;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author LENOVO
 */
public class IfrmLaboratorioAtencion extends javax.swing.JInternalFrame {
    private final LaboratorioLOG laboratorioLOG;
    /**
     * Creates new form IfrmLaboratorioAtencion
     */
    public IfrmLaboratorioAtencion() {
        initComponents();
        this.laboratorioLOG = new LaboratorioLOG();
        
        this.setTitle("Gestión y Atención de Exámenes de Laboratorio");
        this.setClosable(true);
        this.setMaximizable(true);
        this.setIconifiable(true);
        
        cargarTablaExamenes();
    }
    public void cargarTablaExamenes() {
        DefaultTableModel modelo = (DefaultTableModel) tblExamenes.getModel();
        modelo.setRowCount(0);
        try {
            List<ExamenLaboratorio> lista = laboratorioLOG.listarSolicitudesPendientes();
            for (ExamenLaboratorio ex : lista) {
                modelo.addRow(new Object[]{
                    ex.getIdExamen(),
                    ex.getIdPaciente(),
                    ex.getTipoExamen(),
                    ex.getEstado(),
                    ex.getFechaSolicitud()
                });
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al cargar la lista de exámenes: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    private void limpiarCampos() {
        txtIdExamen.setText("");
        txtResultado.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblExamenes = new javax.swing.JTable();
        lblIdExamen = new javax.swing.JLabel();
        txtIdExamen = new javax.swing.JTextField();
        lblResultado = new javax.swing.JLabel();
        txtResultado = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnRefrescar = new javax.swing.JButton();

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitulo.setText("Atencion de Examenes de Laboratorio");

        tblExamenes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID Examen", "ID Atencion", "Tipo Examen", "Estado", "Fecha Solicitud"
            }
        ));
        tblExamenes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblExamenesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblExamenes);

        lblIdExamen.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblIdExamen.setText("ID Examen seleccionado:");

        lblResultado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblResultado.setText("Resultado / Observaciones :");

        btnGuardar.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        btnGuardar.setText("Guardar Resultado");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnRefrescar.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        btnRefrescar.setText("Actualizar Lista");
        btnRefrescar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefrescarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(lblTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblIdExamen)
                            .addComponent(lblResultado))
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtIdExamen, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                            .addComponent(txtResultado)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(btnGuardar)
                        .addGap(112, 112, 112)
                        .addComponent(btnRefrescar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdExamen, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdExamen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblResultado)
                    .addComponent(txtResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRefrescar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(42, 42, 42))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblExamenesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblExamenesMouseClicked
        int fila = tblExamenes.getSelectedRow();
        if (fila >= 0) {
            String idExamen = tblExamenes.getValueAt(fila, 0).toString();
            txtIdExamen.setText(idExamen);
            txtResultado.requestFocus();
        } // TODO add your handling code here:
    }//GEN-LAST:event_tblExamenesMouseClicked

    private void btnRefrescarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefrescarActionPerformed
        cargarTablaExamenes(); // TODO add your handling code here:
    }//GEN-LAST:event_btnRefrescarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        try {
            if (txtIdExamen.getText().trim().isEmpty() || txtResultado.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Debe seleccionar un examen e ingresar el resultado.", "Campos incompletos", JOptionPane.WARNING_MESSAGE);
                return;
            }
            int idExamen = Integer.parseInt(txtIdExamen.getText().trim());
            String resultadoStr = txtResultado.getText().trim();
            boolean exito = laboratorioLOG.registrarResultado(idExamen, resultadoStr, "");
            if (exito) {
                JOptionPane.showMessageDialog(this, "¡Resultado del examen registrado con éxito!", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                limpiarCampos();
                cargarTablaExamenes(); // Refresca la tabla
            } else {
                JOptionPane.showMessageDialog(this, "No se pudo registrar el resultado.", "Error", JOptionPane.ERROR_MESSAGE);
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El ID de Examen debe ser un número entero válido.", "Error de Formato", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error de Negocio", JOptionPane.WARNING_MESSAGE);
        }  // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnRefrescar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblIdExamen;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tblExamenes;
    private javax.swing.JTextField txtIdExamen;
    private javax.swing.JTextField txtResultado;
    // End of variables declaration//GEN-END:variables
}
